#!/usr/bin/env sh
# Block AI attribution markers in added lines. Reads "path:line:content" on stdin.
set -eu
status=0
pattern='Co-[Aa]uthored-[Bb]y|Generated with \[?Claude|noreply@anthropic\.com|Generated by (ChatGPT|Copilot|GPT)|AI-generated by'

while IFS= read -r entry; do
  path=${entry%%:*}
  case "$path" in
    LLM_INSTRUCTIONS.md|.githooks/*|.github/workflows/compliance.yml) continue ;;
  esac
  rest=${entry#*:}; content=${rest#*:}
  if printf '%s' "$content" | grep -qEe "$pattern"; then
    echo "AI attribution marker: ${path}:${rest%%:*}"
    status=1
  fi
done

exit $status
